import os
import sqlite3
import tempfile
import unittest
from unittest.mock import patch

import database


class FakeCursor:
    def __init__(self):
        self.query = None
        self.parameters = None

    def execute(self, query, parameters=None):
        self.query = query
        self.parameters = parameters
        return self

    def fetchone(self):
        return {"id": 42}


class FakeRawConnection:
    def __init__(self):
        self.last_cursor = None

    def cursor(self):
        self.last_cursor = FakeCursor()
        return self.last_cursor


class FakeColumn:
    def __init__(self, name):
        self.name = name


class FakeRowFactoryCursor:
    description = (FakeColumn("id"), FakeColumn("name"))


class DatabaseBackendTests(unittest.TestCase):
    def test_backend_selection_uses_database_url_when_set(self):
        self.assertEqual(database.backend_for_url("postgresql://example"), "postgres")
        self.assertEqual(database.backend_for_url("postgres://example"), "postgres")
        self.assertEqual(database.backend_for_url(""), "sqlite")

    def test_connection_uses_postgres_url_and_normalizes_legacy_scheme(self):
        fake_connection = object()
        with patch.dict(os.environ, {"DATABASE_URL": "postgres://example/db"}):
            with patch.object(database.psycopg, "connect", return_value=fake_connection) as connect:
                conn = database.get_connection()

        connect.assert_called_once()
        self.assertEqual(connect.call_args.args[0], "postgresql://example/db")
        self.assertIs(conn._connection, fake_connection)
        self.assertTrue(database.is_postgres(conn))

    def test_connection_falls_back_to_sqlite_for_explicit_local_path(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = os.path.join(temp_dir, "local.db")
            with patch.dict(os.environ, {}, clear=True):
                conn = database.get_connection(sqlite_path=path)
            try:
                self.assertIsInstance(conn, sqlite3.Connection)
                self.assertEqual(
                    conn.execute("PRAGMA foreign_keys").fetchone()[0],
                    1,
                )
            finally:
                conn.close()

    def test_qmark_conversion_preserves_quoted_text_and_comments(self):
        query = "SELECT '?' AS literal, value FROM items WHERE id=? -- ?\n AND name='it''s ?'"
        self.assertEqual(
            database._qmark_to_format(query),
            "SELECT '?' AS literal, value FROM items WHERE id=%s -- ?\n AND name='it''s ?'",
        )

    def test_hybrid_row_supports_named_and_positional_access(self):
        row = database.HybridRow((("id", 7), ("email", "user@example.test")))
        self.assertEqual(row["id"], 7)
        self.assertEqual(row[0], 7)
        self.assertEqual(row[1], "user@example.test")

    def test_postgres_row_factory_produces_hybrid_rows(self):
        row_maker = database._hybrid_row_factory(FakeRowFactoryCursor())
        row = row_maker((7, "A user"))

        self.assertEqual(row["id"], 7)
        self.assertEqual(row[0], 7)
        self.assertEqual(row["name"], "A user")

    def test_postgres_schema_adaptation_uses_identity_and_matching_types(self):
        statement = (
            "CREATE TABLE IF NOT EXISTS matches ("
            "id INTEGER PRIMARY KEY AUTOINCREMENT, "
            "lost_item_id INTEGER NOT NULL, found_item_id INTEGER NOT NULL, "
            "created_at TEXT DEFAULT CURRENT_TIMESTAMP, "
            "UNIQUE(lost_item_id, found_item_id){match_foreign_keys})"
        )
        adapted = database._adapt_schema_statement(statement, postgres=True)

        self.assertIn("BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", adapted)
        self.assertIn("lost_item_id BIGINT NOT NULL", adapted)
        self.assertIn("found_item_id BIGINT NOT NULL", adapted)
        self.assertIn("DEFAULT (CURRENT_TIMESTAMP::text)", adapted)
        self.assertIn("FOREIGN KEY(lost_item_id) REFERENCES items(id)", adapted)
        self.assertIn("FOREIGN KEY(found_item_id) REFERENCES items(id)", adapted)

    def test_sqlite_initialization_creates_all_application_tables(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            path = os.path.join(temp_dir, "schema.db")
            with patch.dict(os.environ, {}, clear=True):
                with patch.object(database, "DB_NAME", path):
                    database.init_db()
                    conn = database.get_connection()
                    try:
                        tables = {
                            row["name"]
                            for row in conn.execute(
                                "SELECT name FROM sqlite_master WHERE type='table'"
                            )
                        }
                    finally:
                        conn.close()

        self.assertTrue(
            {
                "users",
                "items",
                "claims",
                "matches",
                "audit_logs",
                "messages",
                "notifications",
                "otp_verifications",
                "password_reset_otps",
            }.issubset(tables)
        )

    def test_sqlite_insert_helper_returns_generated_id(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            with patch.dict(os.environ, {}, clear=True):
                conn = database.get_connection(sqlite_path=os.path.join(temp_dir, "test.db"))
                try:
                    conn.execute(
                        "CREATE TABLE claims (id INTEGER PRIMARY KEY AUTOINCREMENT, reason TEXT)"
                    )
                    claim_id = database.insert_returning_id(
                        conn,
                        "INSERT INTO claims(reason) VALUES(?)",
                        ("Proof of ownership",),
                    )
                    self.assertEqual(claim_id, 1)
                finally:
                    conn.close()

    def test_postgres_claim_insert_uses_returning_and_translates_placeholders(self):
        raw_connection = FakeRawConnection()
        conn = database.PostgresConnection(raw_connection)
        claim_id = database.insert_returning_id(
            conn,
            "INSERT INTO claims(reason) VALUES(?)",
            ("Proof of ownership",),
        )

        self.assertEqual(claim_id, 42)
        self.assertEqual(
            raw_connection.last_cursor.query,
            "INSERT INTO claims(reason) VALUES(%s) RETURNING id",
        )
        self.assertEqual(raw_connection.last_cursor.parameters, ("Proof of ownership",))

    def test_admin_transaction_uses_postgres_transaction_lock(self):
        raw_connection = FakeRawConnection()
        conn = database.PostgresConnection(raw_connection)
        database.begin_admin_transaction(conn)

        self.assertEqual(
            raw_connection.last_cursor.query,
            "SELECT pg_advisory_xact_lock(%s)",
        )

    def test_admin_transaction_locks_sqlite_writers(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            with patch.dict(os.environ, {}, clear=True):
                conn = database.get_connection(sqlite_path=os.path.join(temp_dir, "test.db"))
                try:
                    database.begin_admin_transaction(conn)
                    self.assertTrue(conn.in_transaction)
                    conn.rollback()
                finally:
                    conn.close()


if __name__ == "__main__":
    unittest.main()
